spring:
  application:
    name: api-gateway

server:
  port: 1024

eureka:
  client:
    service-url:
       defaultZone: http://localhost:1000/eureka/
  instance:
    # 注册时使用ip而不是主机名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
