spring:
  application:
    name: rbac
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/mkadmin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # druid 配置
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 50
        max-open-prepared-statements: 100
        filters: stat,wall,log4j2
        filter:
          stat:
            merge-sql: true
            slow-sql-millis: 5000
        use-global-data-source-stat: true
        connection-properties: clientEncoding=UTF-8;serverEncoding=UTF-8

server:
  port: 2002

eureka:
  client:
    service-url:
       defaultZone: http://10.0.0.213:1000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    # 注册时使用ip而不是主机名
    prefer-ip-address: true
    # 注册名称显示IP和Port
    #instance-id: ${spring.application.name}:${vcap.application.uris}:${server.port}

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations:
    - classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql